server:
  port: 8380
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_role?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect 
        show_sql: true
        format_sql: true
        
logging:
  level:
    org:
      hibernate:
        type: trace
        
security:
  oauth2:
    resource:
#      jwt:
#        key-value: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2Fpr2FMtWZJvgd+7Tk8kLM6wAJXNx6qtyAL8EkYiHcyxMqV5kBqtc57aw1FFyWAsaNwIFxtt1Mi1rUeigpeb1JwmdJPXZhaW64kn+B/HJAtoIbSbEcYDNIzV8XjyuVZbeEh6PRmXO+iNUoZp63x+x7LnJlN3G2UDFG4xLJifoJubT8CuyidEoZgsYvpEZFJDQzAisEUl9+OO3TTeS726F99wrrXW12I0LfA+CyCT4UdG9lRWWcr17hmjLOU00v9PUmtKx4VpTPoWjF1unfChE97oq4LO7IMJMNjP2qQ024KNPTgg2sQzEyCm06U6+fwl9vkLLnjCQazNgERKuAuO/wIDAQAB-----END PUBLIC KEY-----
      user-info-uri: http://localhost:8280/user
