server:
  port: 8280
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth_jwt?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect 
        show_sql: true
        format_sql: true
        
logging:
  level:
    org:
      hibernate:
        type: trace
        
check-user-scopes: true