server:
  port: 8280
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_role?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect 
        show_sql: true
        format_sql: true
        
logging:
  level:
    org:
      hibernate:
        type: trace
            
config:
  oauth2:
    private-key: -----BEGIN RSA PRIVATE KEY-----MIIEowIBAAKCAQEA2Fpr2FMtWZJvgd+7Tk8kLM6wAJXNx6qtyAL8EkYiHcyxMqV5kBqtc57aw1FFyWAsaNwIFxtt1Mi1rUeigpeb1JwmdJPXZhaW64kn+B/HJAtoIbSbEcYDNIzV8XjyuVZbeEh6PRmXO+iNUoZp63x+x7LnJlN3G2UDFG4xLJifoJubT8CuyidEoZgsYvpEZFJDQzAisEUl9+OO3TTeS726F99wrrXW12I0LfA+CyCT4UdG9lRWWcr17hmjLOU00v9PUmtKx4VpTPoWjF1unfChE97oq4LO7IMJMNjP2qQ024KNPTgg2sQzEyCm06U6+fwl9vkLLnjCQazNgERKuAuO/wIDAQABAoIBAHLtDU6bWIK1O9B0hW3ismeu32VgLjB7JNcTZs1aPfMwcYxixEFdOngpkTGhsX14Pf7xqsaDhoM6nu9OFzBh0qBM1kyk4A3VwBOcBwRR9RnbiVQmOR1m3vsCOP+NbPowumQZs/1S47gqHzAQQKGbv0jbatg8DBAcR1eJ9UsoQ9su81jQUvqbLc6hrzniqzNqzHkaYWi0kKoD9Y10zRADayVF75dwmE4FkHe12HfeRA5pXeOVieyfvD0QF14rqmWLzI9Bmwa5299c7Zm4cqAR4pFTFyX7r+3JmU5EfAbZm94SrGvvHSSsckHyjzhwOWx/sjzH46mD3VUkEW1Tfr6n0fECgYEA8uXEfCbdg/OzUp4w8mlg6ONL0CmTkRFu+Bpy6geBNItwGQ1cz9VCFR29NQeGcbjWHY0F0oUf0dX7xWVn+rVLMBMvDZaFPCiF1FbgaciTZKetEjJ30JTFNePha3MhKq5efA3X0lBhh27yFBXUaHbfrKdAFarvaVAbsz0xD14fBskCgYEA5AYYuy/X2Z+990vk+BMml/2r19iIJDtZDY4CAeEfE6ie3pSO+4C1+80Fq3Eisn0slmRGEb8FqDtpUXTXk4MKseYhffOv+zAca6JbkJ8AuS6NW1234HCKjjrAzA7Q0/QSuypz5WpZUxgTWzyYbcNK1xDkgtEvt0DQNtIFlyb1o4cCgYEAvbGvp3361YhHbahZdZfStU598M3njw3cairNv/Oodk7Hduk2qKFWAIO/NmDwIHRH08BE4cpRtWC2Rc0STXu0gpEY2DXLS9Yh3lkS3cplQeCpi2Kaq+zjr1iOvYmmR1zyMVPmTzuzTz/YEtORlRvxRzc/Fyzt2INVfr+1RtksxfECgYB7r6bomnoOLO0hYESSH+k2Vr5I9cZbSOn0RUxncpKl2jha6eBpIhcUv9BMf7DferCd30R2ydQqvhdRvPxWoqVBfGA8btvNd/pilA3w856z1EGPBtX/42v03H/J8FtsLR+f8NYu4jITtaKCQes41s8Yu6wIHaoxT/HhWqj3pYVmrwKBgDw1j84jeobn3AAJ824j3XWAR63sQGA1m759AVmm7twR9L8/6JClK3PINO2nHe+kpSedHsJrOe3ZGKb+ETS7Egz35x9FtjHtB83u0xUzDUXTNzrtPsFlSAwB0/orjyIOzzE9rbBbb3kV04LsgDfPbhR+y+C2U6/DLPjpWuWe9yd/-----END RSA PRIVATE KEY-----
    public-key: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2Fpr2FMtWZJvgd+7Tk8kLM6wAJXNx6qtyAL8EkYiHcyxMqV5kBqtc57aw1FFyWAsaNwIFxtt1Mi1rUeigpeb1JwmdJPXZhaW64kn+B/HJAtoIbSbEcYDNIzV8XjyuVZbeEh6PRmXO+iNUoZp63x+x7LnJlN3G2UDFG4xLJifoJubT8CuyidEoZgsYvpEZFJDQzAisEUl9+OO3TTeS726F99wrrXW12I0LfA+CyCT4UdG9lRWWcr17hmjLOU00v9PUmtKx4VpTPoWjF1unfChE97oq4LO7IMJMNjP2qQ024KNPTgg2sQzEyCm06U6+fwl9vkLLnjCQazNgERKuAuO/wIDAQAB-----END PUBLIC KEY-----
    